### ISSUE TITLE
`doteur` panics if table-name is wrapped by double-quotations

### ISSUE THREAD

**Issue by raunakab** [nag763/doteur#1]
**Describe the bug**
`doteur` can successfully compile the following command:

    ``` test.sql
    CREATE TABLE my_table_name ( ... );
    ```

but the following will throw an error:

    ``` test.sql
    CREATE TABLE "my_table_name" ( ... );
    ```

`doteur`, however, does NOT panic if column-names are wrapped in double-quotations.
i.e., `doteur` will successfully compile the following (even though the column-name is wrapped in double-quotations):

    ``` test.sql
    CREATE TABLE my_table_name (
        "my_column" INT
    );
    ```

It seems that the panic only happens when the TABLE-NAME is wrapped in double-quotes...

**To Reproduce**
1. create a `test.sql` file
2. write:
        CREATE TABLE "my_table_name" ( "id" INT );
3. the above will fail, but if you change it to:
        CREATE TABLE my_table_name ( "id" INT );
    if will compile and produce an output

**Expected behavior**
`doteur` should not panic if a table-name is wrapped with double-quotations.

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by raunakab** [comment]
btw, really amazing project!

**Comment by nag763** [comment]
Hello @raunakab 

I am delighted to see that you are my very first issue reporter 😄 

I have a concern with the issue you reported :

I tested today in my local environment, and double-quotated tables name aren't accepted by the MySQL engine (tried on 8.0.27 on Ubuntu).

See below :

```mysql
mysql> CREATE DATABASE foo;
Query OK, 1 row affected (0.01 sec)
mysql> USE foo;
Database changed
mysql> CREATE TABLE "my_table_name" (      my_column INT  );
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"my_table_name" (      my_column INT  )' at line 1
```

However, from what I saw, maybe the confusion comes from the fact that column name are interpreted by the program despite being rejected by the MySQL engine : 

```mysql
mysql> CREATE TABLE my_table_name (      "my_column" INT  );
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"my_column" INT  )' at line 1
```

Could you tell me whether : 
* The program shouldn't be accepting columns with double-quotations ?
* Or if the double-quotation syntax has been added/ dropped in any release of the mysql engine ?

---

Thanks in advance for your feedback and your heartful comment, it is a pleasure to see you tried my program (and apparently liked it) 👍 😄

**Comment by raunakab** [comment]
Hey,

So I believe that PostgreSQL, MySQL, etc., have different standards when it comes to wrapping identifiers with quotes.
In PostgreSQL, identifiers are wrapped in double-quotes, whereas MySQL uses back-ticks, I believe...

This may explain why you were not able to use double-quotes with a MySQL db.

Cheers!

**Comment by raunakab** [comment]
(Oh, I also forgot to mention, I am using PostgreSQL as my db engine)

**Comment by raunakab** [comment]
Also, I reread the README, and it looks like you have crafted this tool for a MySQL db specifically. Is that correct?

If so, then I should have read the README more thoroughly, but do you know if you are planning on supporting additional SQL standards for future iterations?

Thanks!

**Comment by nag763** [comment]
> Also, I reread the README, and it looks like you have crafted this tool for a MySQL db specifically. Is that correct?

Yes indeed, my first purpose was to support the MySQL engine.

> If so, then I should have read the README more thoroughly, but do you know if you are planning on supporting additional SQL standards for future iterations?

I wish ! From what I saw, the postgres syntax is pretty similar to the mysql one bar some subtilites. I will try to see if it could be done quickly and keep you up to date 😄

**Comment by nag763** [comment]
Dear @raunakab,

The first results look quite promising ! 😄 

I tried with some sample files and created a [dedicated branch on purpose](https://github.com/nag763/doteur/tree/postgres_support).

As my knowledge about postgres structures is pretty limited so far, could you give me a feedback on the following items :

* Should the `public` attribute appear next to an attribute / table name or is it unecessary ?
* Can you check the zip file I attached ( [postgres_support_sample_and_outputs.zip](https://github.com/nag763/doteur/files/7604977/postgres_support_sample_and_outputs.zip) ), it contains some examples with either some simple and complex database files. If you are lazy, just check the `{outpout}.png` files 😛 

I am open to any suggestion and feedback, as I said my postgres knowledge is rather limited ! 

Regards,

Loïc

**Comment by nag763** [comment]
May I add that if you want to carry your own tests, and got cargo installed on your workstation, you can try with your own scripts by installing directly the branch with : 

```bash
cargo install --git https://github.com/nag763/doteur/ --branch postgres_support
```
