### ISSUE TITLE
BUG: Inline comments in table def cause errors about <B> elements

### ISSUE THREAD

**Issue by jmetz** [nag763/doteur#6]
**Describe the bug**
When outputting to `png` or calling `dot` on the generated `.dot` file, I get errors about `<B></B>` elements, 
when including inline comments in a table definition. 

**To Reproduce**
1. Use simple sql, eg in file named `basic.sql`: 
```sql
-- Table: users
CREATE TABLE users (
    user_id VARCHAR PRIMARY KEY, -- Some test comment here
);
```
2. Run eg `doteur  basic.sql  -o basic.png` 

**Output**

```
The output has been successfully written to the basic.png file
Error: syntax error in line 16 
... <B></B> ...
in label of node users
```

**Expected behavior**
I expected the comment to be at least ignored or ideally included in the diagram properly. 

If I remove the inline comment, `doteur` functions correctly: 

![image](https://github.com/user-attachments/assets/3b8c05d6-fc04-4d44-a8a1-5417d67a9ff4)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Not used
 - Version 0.5.3

**Comment by nag763** [comment]
Hello dear @jmetz 

This has been adressed in e813572

Checking in the [live tester](https://nag763.github.io/doteur/live/) before :

![image](https://github.com/user-attachments/assets/1351b6ae-d913-4398-bab0-2db3015a8a9e)

Past CICD refresh : 

![image](https://github.com/user-attachments/assets/0c7cf274-a8cf-4f50-a8ba-6f4aaf317548)

Wishing you a wonderful day ahead !
